spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-password: springboot
    keyStoreType: PKCS12
    keyAlias: tomcat

fotobox:
  save-path: 'C:/Users/m.hofstetter/test/'